### PR TITLE
Update for base url

### PR DESCRIPTION
**Pull request by junedkh**
No More Require Base Url Only For **_Heroku_**

### CODE REVIEW

**Comment by junedkh** [comment]
@junedkh @hafitzXD check

**Comment by yourtulloh** [comment]
you forgot vps users, vpn users use herokuapp.com? Base url is not for alive only but for selecting torrent

**Comment by junedkh** [comment]
@yourtulloh Yes I set it only for base URL if Heroku app name in not none

**Comment by cArN4gEisDeD** [comment]
@junedkh Tf is he saying lmao

**Comment by junedkh** [comment]
@cArN4gEisDeD I mean if isvps is true it will not set base URL from Heroku app name

**Comment by junedkh** [comment]
@junedkh

**Comment by anasty17** [comment]
> @yourtulloh Yes I set it only for base URL if Heroku app name in not none

No need bro it's just small var ...

**Comment by junedkh** [comment]
okay close it. i try this because everyday one guy come and ask why bot is not up 😁😁 i was trying to fix that

**Comment by anasty17** [comment]
> okay close it. i try this because everyday one guy come and ask why bot is not up 😁😁 i was trying to fix that

Commit for config file only

**Pull request closed without merging**
